stages:
  create_dataset:
    cmd: python create_dataset.py
    deps:
    - Kaggle_ds
    - create_dataset.py
    params:
    - with_augmentation
    outs:
    - dataset
  train_model:
    cmd: python train_model.py
    deps:
    - dataset
    - train_model.py
    outs:
    - models
